name: uMCX CI

on: [push, pull_request]

jobs:
  no_gpu_test:
    name: CPU test
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Build binary
        run: |
          g++ --version
          cd src
          make
      - name: Run tests
        run: |
          cd test
          ./testumcx.sh

  nvptx_gpu_offloading_test:
    name: NVIDIA GPU nvptx test
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get install gcc-11 g++-11 gcc-12 g++-12 gcc-13 g++-13 gcc-11-offload-nvptx gcc-12-offload-nvptx gcc-13-offload-nvptx -y
      - name: Build binary g++-11
        run: |
          cd src
          make clean
          make nvidia CXX=g++-11
      - name: Build binary g++-12
        run: |
          cd src
          make clean
          make nvidia CXX=g++-12
      - name: Build binary g++-13
        run: |
          cd src
          make clean
          make nvidia CXX=g++-13
